In [122]:
dataset_2 = data

In [123]:
import pandas as pd
import numpy as np

In [124]:
data = pd.read_csv('dataset_with_public_holidays.csv')

In [125]:
train_data = data[['Date', 'monthly_index', 'Daily global solar exposure (MJ/m*m)']]

In [126]:
train_data

Date  monthly_index  Daily global solar exposure (MJ/m*m)
0     2015-01-01              1                                  23.6
1     2015-01-02              1                                  26.8
2     2015-01-03              1                                  26.5
3     2015-01-04              1                                  25.2
4     2015-01-05              1                                  30.7
...          ...            ...                                   ...
2127  2020-10-27             10                                  20.1
2128  2020-10-28             10                                  26.7
2129  2020-10-29             10                                  17.1
2130  2020-10-30             10                                  21.0
2131  2020-10-31             10                                  10.0

[2132 rows x 3 columns]

In [127]:
train_data['Date'] = train_data['Date'].astype('datetime64[ns]')

In [128]:
train_data['Day'] = train_data.Date.dt.day
train_data['Year'] = train_data.Date.dt.year
train_data['day_of_year'] = train_data.Date.dt.dayofyear

In [129]:
x_train = train_data[['Year', 'monthly_index', 'Day', 'day_of_year']]
y_train = train_data[['Daily global solar exposure (MJ/m*m)']]

In [130]:
x_train

Year  monthly_index  Day  day_of_year
0     2015              1    1            1
1     2015              1    2            2
2     2015              1    3            3
3     2015              1    4            4
4     2015              1    5            5
...    ...            ...  ...          ...
2127  2020             10   27          301
2128  2020             10   28          302
2129  2020             10   29          303
2130  2020             10   30          304
2131  2020             10   31          305

[2132 rows x 4 columns]

In [131]:
y_train['Daily global solar exposure (MJ/m*m)'] = y_train['Daily global solar exposure (MJ/m*m)'].fillna(0)

In [132]:
rng = pd.date_range('2020-11-01', periods=92, freq='D')
data2 = pd.DataFrame({ 'Date': rng}) 
data2

Date
0  2020-11-01
1  2020-11-02
2  2020-11-03
3  2020-11-04
4  2020-11-05
..        ...
87 2021-01-27
88 2021-01-28
89 2021-01-29
90 2021-01-30
91 2021-01-31

[92 rows x 1 columns]

In [133]:
data2['Date'] = data2['Date'].astype('datetime64[ns]')

In [134]:
test_data = data2.copy()
test_data['Day'] = data2.Date.dt.day
test_data['Year'] = data2.Date.dt.year
test_data['day_of_year'] = data2.Date.dt.dayofyear
test_data['monthly_index'] = data2.Date.dt.month
data2


Date
0  2020-11-01
1  2020-11-02
2  2020-11-03
3  2020-11-04
4  2020-11-05
..        ...
87 2021-01-27
88 2021-01-28
89 2021-01-29
90 2021-01-30
91 2021-01-31

[92 rows x 1 columns]

In [135]:
test_data.drop(columns=['Date'], inplace = True)

In [136]:
test_data = test_data[['Year', 'monthly_index', 'Day', 'day_of_year']]
test_data

Year  monthly_index  Day  day_of_year
0   2020             11    1          306
1   2020             11    2          307
2   2020             11    3          308
3   2020             11    4          309
4   2020             11    5          310
..   ...            ...  ...          ...
87  2021              1   27           27
88  2021              1   28           28
89  2021              1   29           29
90  2021              1   30           30
91  2021              1   31           31

[92 rows x 4 columns]

In [137]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
sc = StandardScaler()
min = MinMaxScaler()

In [138]:
train_data = sc.fit_transform(x_train)
test_data = sc.fit_transform(test_data)

In [139]:
train_data = min.fit_transform(train_data)
test_data = min.fit_transform(test_data)

In [140]:
test_data

array([[0.        , 0.90909091, 0.        , 0.83561644],
       [0.        , 0.90909091, 0.03333333, 0.83835616],
       [0.        , 0.90909091, 0.06666667, 0.84109589],
       [0.        , 0.90909091, 0.1       , 0.84383562],
       [0.        , 0.90909091, 0.13333333, 0.84657534],
       [0.        , 0.90909091, 0.16666667, 0.84931507],
       [0.        , 0.90909091, 0.2       , 0.85205479],
       [0.        , 0.90909091, 0.23333333, 0.85479452],
       [0.        , 0.90909091, 0.26666667, 0.85753425],
       [0.        , 0.90909091, 0.3       , 0.86027397],
       [0.        , 0.90909091, 0.33333333, 0.8630137 ],
       [0.        , 0.90909091, 0.36666667, 0.86575342],
       [0.        , 0.90909091, 0.4       , 0.86849315],
       [0.        , 0.90909091, 0.43333333, 0.87123288],
       [0.        , 0.90909091, 0.46666667, 0.8739726 ],
       [0.        , 0.90909091, 0.5       , 0.87671233],
       [0.        , 0.90909091, 0.53333333, 0.87945205],
       [0.        , 0.90909091,

In [141]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [142]:
mlp_reg = MLPRegressor()
dct = DecisionTreeRegressor(max_depth=None)
knn = KNeighborsRegressor(n_neighbors=3)
rf = RandomForestRegressor()

In [143]:
mlp_reg.fit(train_data, y_train)
dct.fit(train_data, y_train)
knn.fit(train_data, y_train)
rf.fit(train_data, y_train)

RandomForestRegressor()

In [144]:
scores = cross_val_score(dct, train_data, y_train, scoring='neg_mean_squared_error', cv=5)

In [145]:
scores

array([-60.7265808 , -52.23250585, -50.08830986, -44.25215962,
       -53.45507042])

In [146]:
mlp_reg.predict(test_data)

array([18.5323971 , 18.56392628, 18.59545546, 18.62235556, 18.64756875,
       18.67278193, 18.69799512, 18.7232083 , 18.74842149, 18.77363467,
       18.79884786, 18.82406105, 18.84927423, 18.87448742, 18.8997006 ,
       18.92491379, 18.95012697, 18.97534016, 19.00055334, 19.02576653,
       19.05097971, 19.0761929 , 19.10140609, 19.12661927, 19.15183246,
       19.17704564, 19.20225883, 19.22747201, 19.2526852 , 19.27789838,
       19.95240625, 19.98393543, 20.01546461, 20.04699378, 20.07715529,
       20.10236847, 20.12758166, 20.15279484, 20.17800803, 20.20322121,
       20.2284344 , 20.25364758, 20.27886077, 20.30407396, 20.32928714,
       20.35450033, 20.37971351, 20.4049267 , 20.43013988, 20.45535307,
       20.48056625, 20.50577944, 20.53099262, 20.55620581, 20.581419  ,
       20.60663218, 20.63184537, 20.65705855, 20.68227174, 20.70748492,
       20.73268485, 22.37122984, 22.30088267, 22.23106023, 22.1612378 ,
       22.09318855, 22.02578667, 21.95838479, 21.89098291, 21.82

In [147]:
dct.predict(test_data)

array([10. ,  8.2, 19.6, 19.6,  3.7, 25.2, 25.1, 26.4, 26.4,  5.3, 19.2,
       19.2, 27.5, 27.6, 27.6, 25.8, 28.8, 20.6, 29.9, 22.1, 19.8, 27.3,
       30. , 30. ,  9.3, 23.3, 16.8, 24.4, 31. ,  9.6, 24.4, 32.4, 31.2,
       32.2, 13.5, 13.5, 30.8, 11.6, 23.2, 13. , 13. , 28.6, 31.6, 31.6,
       30.8, 33.1, 33.1, 31.2, 29.3, 25.4, 32.9, 32.9, 32.4, 33.3, 33.3,
       27.6, 33.2, 33.2, 33. , 28.8, 29.6, 31.6, 31.6, 30.7, 22.8,  5.1,
        2.7,  7.7, 26.9, 29.8, 10.1, 18.2, 21.9, 28.1, 27.4, 20.8, 18.6,
       24.4, 27.2, 23.9,  8.8, 28.4, 12.4, 13.4, 20.6, 30. , 24. , 26.1,
       26.5, 29.5, 29.3, 18.3])

In [148]:
param_grid = {"criterion": ["mse",'friedman_mse'],
              "min_samples_split": [2,3],
              "max_depth": [100,200,None]
              }

In [149]:
grid_cv_dtm = GridSearchCV(dct, param_grid, cv=5, scoring = 'neg_mean_absolute_error')

In [150]:
grid_cv_dtm.fit(train_data, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['mse', 'friedman_mse'],
                         'max_depth': [100, 200, None],
                         'min_samples_split': [2, 3]},
             scoring='neg_mean_absolute_error')

In [151]:
grid_cv_dtm.best_score_

-4.8719769436289875

In [152]:
predict = grid_cv_dtm.predict(test_data)

In [153]:
test_data


array([[0.        , 0.90909091, 0.        , 0.83561644],
       [0.        , 0.90909091, 0.03333333, 0.83835616],
       [0.        , 0.90909091, 0.06666667, 0.84109589],
       [0.        , 0.90909091, 0.1       , 0.84383562],
       [0.        , 0.90909091, 0.13333333, 0.84657534],
       [0.        , 0.90909091, 0.16666667, 0.84931507],
       [0.        , 0.90909091, 0.2       , 0.85205479],
       [0.        , 0.90909091, 0.23333333, 0.85479452],
       [0.        , 0.90909091, 0.26666667, 0.85753425],
       [0.        , 0.90909091, 0.3       , 0.86027397],
       [0.        , 0.90909091, 0.33333333, 0.8630137 ],
       [0.        , 0.90909091, 0.36666667, 0.86575342],
       [0.        , 0.90909091, 0.4       , 0.86849315],
       [0.        , 0.90909091, 0.43333333, 0.87123288],
       [0.        , 0.90909091, 0.46666667, 0.8739726 ],
       [0.        , 0.90909091, 0.5       , 0.87671233],
       [0.        , 0.90909091, 0.53333333, 0.87945205],
       [0.        , 0.90909091,

In [154]:
data2

Date
0  2020-11-01
1  2020-11-02
2  2020-11-03
3  2020-11-04
4  2020-11-05
..        ...
87 2021-01-27
88 2021-01-28
89 2021-01-29
90 2021-01-30
91 2021-01-31

[92 rows x 1 columns]

In [156]:
data2['day'] = data2.Date.dt.day
data2['monthly_index'] = data2.Date.dt.month
data2['Daily global solar exposure (MJ/m*m)'] = predict

In [157]:
data2

Date  day  monthly_index  Daily global solar exposure (MJ/m*m)
0  2020-11-01    1             11                                 10.00
1  2020-11-02    2             11                                  8.20
2  2020-11-03    3             11                                 18.00
3  2020-11-04    4             11                                 18.00
4  2020-11-05    5             11                                  3.70
..        ...  ...            ...                                   ...
87 2021-01-27   27              1                                 26.30
88 2021-01-28   28              1                                 26.30
89 2021-01-29   29              1                                 29.40
90 2021-01-30   30              1                                 29.40
91 2021-01-31   31              1                                 18.35

[92 rows x 4 columns]

In [158]:
data2.to_csv ('test_data.csv', index = False, header=True)