In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import warnings
from datetime import datetime, timedelta
warnings.filterwarnings("ignore")

In [2]:
rainfall  = pd.read_csv('rainfall_dataset.csv')
df = rainfall[['date', 'Rainfall amount (millimetres)']]
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')

rainfall

date  Year Month day of week  Rainfall amount (millimetres)
0     2015-01-01  2015   Jan    Thursday                            0.0
1     2015-01-02  2015   Jan      Friday                            0.0
2     2015-01-03  2015   Jan    Saturday                            0.0
3     2015-01-04  2015   Jan      Sunday                            4.2
4     2015-01-05  2015   Jan      Monday                            0.0
...          ...   ...   ...         ...                            ...
2246  2021-02-24  2021   Feb   Wednesday                            0.0
2247  2021-02-25  2021   Feb    Thursday                            0.0
2248  2021-02-26  2021   Feb      Friday                            0.4
2249  2021-02-27  2021   Feb    Saturday                            0.0
2250  2021-02-28  2021   Feb      Sunday                            0.0

[2251 rows x 5 columns]

In [3]:
#get columns with number value
df['month'] = df['date'].dt.month
df['dayofweek']= df['date'].dt.dayofweek+1
df['dayofyear'] = df['date'].dt.dayofyear
df['year'] = df['date'].dt.year

#order column
col = ['dayofyear','dayofweek', 'month', 'year', 'Rainfall amount (millimetres)']
df = df[col]
df

dayofyear  dayofweek  month  year  Rainfall amount (millimetres)
0             1          4      1  2015                            0.0
1             2          5      1  2015                            0.0
2             3          6      1  2015                            0.0
3             4          7      1  2015                            4.2
4             5          1      1  2015                            0.0
...         ...        ...    ...   ...                            ...
2246         55          3      2  2021                            0.0
2247         56          4      2  2021                            0.0
2248         57          5      2  2021                            0.4
2249         58          6      2  2021                            0.0
2250         59          7      2  2021                            0.0

[2251 rows x 5 columns]

In [4]:
#check missing value 
df.isnull().sum()

dayofyear                        0
dayofweek                        0
month                            0
year                             0
Rainfall amount (millimetres)    0
dtype: int64

In [5]:
#date shape
df.shape

(2251, 5)

In [6]:
#train data range 2015 - 2020
#test data in 2021
#train_condition = (2015 <= df['year']) & (df['year']< 2021)
#test_condition = df['year']>=2021
#
#train_data = df[train_condition]
#test_data = df[test_condition]
#X_train = train_data.iloc[:,:-1]
#Y_train = train_data.iloc[:,-1]
#print(X_train, Y_train)
#X_test = test_data.iloc[:,:-1]
#Y_test = test_data.iloc[:,-1]

**split dataset**

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.33, random_state=42 )


In [8]:
X_train

dayofyear  dayofweek  month  year
1976        151          6      5  2020
265         266          3      9  2015
376          12          2      1  2016
1352        257          5      9  2018
1508         48          7      2  2019
...         ...        ...    ...   ...
1638        178          4      6  2019
1095        365          7     12  2017
1130         35          7      2  2018
1294        199          3      7  2018
860         130          3      5  2017

[1508 rows x 4 columns]

In [9]:
X_test

dayofyear  dayofweek  month  year
1666        206          4      7  2019
1809        349          7     12  2019
582         218          5      8  2016
247         248          6      9  2015
1820        360          4     12  2019
...         ...        ...    ...   ...
2             3          6      1  2015
2228         37          6      2  2021
576         212          6      7  2016
1436        341          5     12  2018
339         340          7     12  2015

[743 rows x 4 columns]

In [10]:
y_train

1976    0.0
265     0.0
376     0.8
1352    0.0
1508    0.0
       ... 
1638    0.0
1095    0.2
1130    0.0
1294    1.2
860     0.0
Name: Rainfall amount (millimetres), Length: 1508, dtype: float64

In [11]:
y_test

1666    0.0
1809    0.0
582     0.0
247     0.0
1820    0.0
       ... 
2       0.0
2228    1.6
576     2.4
1436    0.0
339     0.0
Name: Rainfall amount (millimetres), Length: 743, dtype: float64

In [12]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler


In [13]:
#using standard scaler
scaler = StandardScaler()
#fit get the mean and standard deviation of the train features 
#while tranform applies the standardation formular
X_train_StandardScaler = scaler.fit_transform(X_train) 
X_train_StandardScaler

array([[-0.258987  ,  1.00591117, -0.39424171,  1.36408862],
       [ 0.81056091, -0.49846639,  0.74467879, -1.47321571],
       [-1.55174491, -0.99992558, -1.53316222, -0.90575484],
       ...,
       [-1.33783533,  1.50737035, -1.2484321 ,  0.22916689],
       [ 0.187433  , -0.49846639,  0.17521854,  0.22916689],
       [-0.45429575, -0.49846639, -0.39424171, -0.33829398]])

In [14]:
X_test_StandardScaler = scaler.fit_transform(X_test) 
X_test_StandardScaler

array([[ 0.24798612, -0.01003914,  0.17293131,  0.78510655],
       [ 1.60008121,  1.48177702,  1.6133793 ,  0.78510655],
       [ 0.36144864,  0.48723291,  0.46102091, -0.87839392],
       ...,
       [ 0.30471738,  0.98450497,  0.17293131, -0.87839392],
       [ 1.52443953,  0.48723291,  1.6133793 ,  0.23060639],
       [ 1.51498432,  1.48177702,  1.6133793 , -1.43289408]])

# KNN

In [15]:
#KNN parameters
n_neighbors = [2,4,5,10,25]
leaf_size = [10,20,30,50,100,500]
metric = ['euclidean','chebyshev','manhattan']
weights = ['uniform', 'distance']
algorithm = ['auto', 'ball_tree', 'kd_tree', 'brute'] 


#declaring parameters for KNN algorithm to determine it performance on the test data
scores_ = []
neighbor = []
leaf_size_ = []
metric_ = []
weight = []
algorithm_ = []

for i in n_neighbors:
  for j in leaf_size:
    for k in metric:
      for l in weights:
        for m in algorithm:
          knn_maxi = KNeighborsRegressor(n_neighbors = i, leaf_size = j, metric = k, weights = l, algorithm = m)
          knn_maxi.fit(X_train_StandardScaler, y_train)
          scores_.append(mean_squared_error(y_test.values, knn_maxi.predict(X_test_StandardScaler)))
          
          neighbor.append(i)
          leaf_size_.append(j)
          metric_.append(k)
          weight.append(l)
          algorithm_.append(m)


In [16]:
#checking the minimun mean square error of the KNN algorithm used for rainfall prediction
min(scores_)

27.191755365797736

In [17]:
#getting the index of the minimun mean square error of the KNN algorithm from the list
index_max = np.argmin(scores_)
index_max

585

In [18]:
#obtaining the parameters with the minimun mean square error of the KNN algorithm 
rainfall_knn_parameters = [neighbor[index_max], leaf_size_[index_max], metric_[index_max], weight[index_max], algorithm_[index_max]]
rainfall_knn_parameters

[25, 10, 'chebyshev', 'uniform', 'ball_tree']

In [19]:
#assign best parameter
knn_max = KNeighborsRegressor(n_neighbors = neighbor[index_max], leaf_size = leaf_size_[index_max],  metric = metric_[index_max], weights = weight[index_max], algorithm = algorithm_[index_max])
knn_max.fit(X_train_StandardScaler, y_train)


KNeighborsRegressor(algorithm='ball_tree', leaf_size=10, metric='chebyshev',
                    n_neighbors=25)

In [20]:
knn_max.predict(X_test_StandardScaler)[:5]


array([1.288, 1.568, 2.128, 0.176, 1.24 ])

In [21]:
#printing the test data side by side with the predicted data
np.concatenate((y_test.values.reshape(len(y_test),1), knn_max.predict(X_test_StandardScaler).reshape(len(y_test),1)),1)

array([[0.   , 1.288],
       [0.   , 1.568],
       [0.   , 2.128],
       ...,
       [2.4  , 2.568],
       [0.   , 1.84 ],
       [0.   , 1.8  ]])

## MLP

In [22]:
hidden_layer_sizes = []
for i in range(1,10):
  hidden_layer_sizes.append(((i,i,i)))

activation = ['tanh', 'relu', 'logistic', 'identity']
solver = ['lbfgs', 'sgd', 'adam']
alpha = [0.0001, 0.05, 0.01, .001]
learning_rate = ['constant','adaptive', 'invscaling']

In [24]:
#MLP for rainfall 

#declaring parameters for MLP algorithm to determine it performance on the test data
scores_mlp_max_rainfall = []
hidden_layer_sizes_ = []
solver_ = []
activation_ = []
alpha_ = []
learning_rate_ = []


for i in hidden_layer_sizes:
  for j in activation:
    for k in solver:
      for l in alpha:
        for m in learning_rate:

          mlp_maxi = MLPRegressor(hidden_layer_sizes = i, activation = j, solver = k, alpha = l, learning_rate = m)
          mlp_maxi.fit(X_train_StandardScaler, y_train)
       
          scores_mlp_max_rainfall.append(mean_squared_error(y_test.values, knn_maxi.predict(X_test_StandardScaler)))
          hidden_layer_sizes_.append(i)
          activation_.append(j)
          solver_.append(k)
          alpha_.append(l)
          learning_rate_.append(m)

In [28]:
#checking the minimun mean square error of the MLP algorithm used for prediction
min(scores_mlp_max_rainfall)

28.080610717110428

In [29]:
#getting the index of the minimun mean square error of the KNN algorithm from the list
index_min = np.argmin(scores_mlp_max_rainfall)
index_min

0

In [30]:
#obtaining the parameters with the minimun mean square error of the mlp algorithm 
rainfall_mlp_parameters = [hidden_layer_sizes_[index_max], activation_[index_max], solver_[index_max], alpha_[index_max], learning_rate_[index_max]]
rainfall_mlp_parameters

[(5, 5, 5), 'tanh', 'lbfgs', 0.001, 'constant']

In [32]:
mlp_max = MLPRegressor(hidden_layer_sizes = (2, 2, 2), activation = 'relu', solver = 'sgd' , alpha = 0.001, learning_rate = 'invscaling')
mlp_max.fit(X_train_StandardScaler, y_train)

MLPRegressor(alpha=0.001, hidden_layer_sizes=(2, 2, 2),
             learning_rate='invscaling', solver='sgd')

In [33]:
#printing the test data side by side with the predicted data
np.concatenate((y_test.values.reshape(len(y_test),1), mlp_max.predict(X_test_StandardScaler).reshape(len(y_test),1)),1)

array([[ 0.        , -0.41538732],
       [ 0.        , -0.41538732],
       [ 0.        , -0.2529807 ],
       ...,
       [ 2.4       , -0.20335721],
       [ 0.        , -0.41538732],
       [ 0.        , -0.24241638]])

## Decision tree

In [34]:
splitter=['best','random']
criterion = ['mse', 'friedman_mse', 'mae']
max_depth = [1,2,3,4,5,10,20,30,40]
max_features =['auto','sqrt','log2'] 
min_samples_split= [2,3,4,5,10,20,30,40]
random_state= [1,2,3,4,5,6,7,8,9,42]

In [35]:
#DT for Maximum Temperature

#declaring parameters for DT algorithm to determine it performance on the test data
scores_dt_rainfall = []
splitter_ = []
criterion_ =  []
max_depth_ = []
max_features_ = []
min_samples_split_ = []
random_state_ = []


for i in splitter:
  for j in criterion:
    for k in max_depth:
      for l in max_features:
        for m in min_samples_split:
          for n in random_state:
            dt_maxi = DecisionTreeRegressor(splitter = i, criterion = j, max_depth = k, max_features = l, min_samples_split = m,random_state = n )
            dt_maxi.fit(X_train_StandardScaler, y_train)
            
            scores_dt_rainfall.append(mean_squared_error(y_test.values, knn_maxi.predict(X_test_StandardScaler)))

            splitter_.append(i)
            criterion_.append(j)
            max_depth_.append(k)
            max_features_.append(l)
            min_samples_split_.append(m)
            random_state_.append(n)

In [36]:
#checking the minimun mean square error of the dt algorithm used for rainfall prediction
min(scores_dt_rainfall)

28.080610717110428

In [37]:
#getting the index of the minimun mean square error of the dt algorithm from the list
index_max = np.argmin(scores_dt_rainfall)
index_max

0

In [38]:
#obtaining the parameters with the minimun mean square error of the DT algorithm 
rainfall_dt_parameters = [splitter_[index_max], criterion_[index_max], max_depth_[index_max], max_features_[index_max], min_samples_split_[index_max],random_state_[index_max]]
rainfall_dt_parameters

['best', 'mse', 1, 'auto', 2, 1]

In [61]:
dt_max = DecisionTreeRegressor(splitter = splitter_[index_max] , criterion = criterion_[index_max], max_depth = max_depth_[index_max], max_features = max_features_[index_max], min_samples_split = min_samples_split_[index_max],random_state = random_state_[index_max])
dt_max.fit(X_train_StandardScaler, y_train)

DecisionTreeRegressor(max_depth=10, max_features='auto', min_samples_split=10,
                      random_state=1)

In [62]:
#printing the test data side by side with the predicted data
np.concatenate((y_test.values.reshape(len(y_test),1), dt_max.predict(X_test_StandardScaler).reshape(len(y_test),1)),1)

array([[0.        , 1.12171351],
       [0.        , 0.        ],
       [0.        , 2.30740741],
       ...,
       [2.4       , 2.30740741],
       [0.        , 9.68      ],
       [0.        , 5.43333333]])

## Random Forest

In [40]:
criterion = ['mse', 'friedman_mse', 'mae']
max_depth = [10,20,30,40]
max_features =['auto','sqrt','log2'] 
min_samples_split= [10,20,30,40]
random_state= [1,2,3,42]
n_estimators =[10,50,100]

In [43]:
#RF for rainfall

#declaring parameters for RF algorithm to determine it performance on the test data
scores_rf_rainfall = []
n_estimators_ = []
criterion_ =  []
max_depth_ = []
max_features_ = []
min_samples_split_ = []
random_state_ = []


for i in n_estimators:
  for j in criterion:
    for k in max_depth:
      for l in max_features:
        for m in min_samples_split:
          for n in random_state:
            rf_maxi = RandomForestRegressor(n_estimators = i, criterion = j, max_depth = k, max_features = l, min_samples_split = m,random_state = n )
            rf_maxi.fit(X_train_StandardScaler, y_train)
            scores_rf_rainfall.append(mean_squared_error(y_test.values, knn_maxi.predict(X_test_StandardScaler)))

            n_estimators_.append(i)
            criterion_.append(j)
            max_depth_.append(k)
            max_features_.append(l)
            min_samples_split_.append(m)
            random_state_.append(n)

In [44]:
min(scores_rf_rainfall)

28.080610717110428

In [45]:
index_max = np.argmin(scores_rf_rainfall)
index_max

0

In [46]:
#obtaining the parameters with the minimun mean square error of the RF algorithm 
scores_rf_rainfall_parameters = [n_estimators_[index_max], criterion_[index_max], max_depth_[index_max], max_features_[index_max],min_samples_split_[index_max],random_state_[index_max] ]
scores_rf_rainfall_parameters

[10, 'mse', 10, 'auto', 10, 1]

In [47]:
rf_max = RandomForestRegressor(n_estimators = n_estimators_[index_max], criterion = criterion_[index_max], max_depth = max_depth_[index_max], max_features =  max_features_[index_max], min_samples_split = min_samples_split_[index_max],random_state = random_state_[index_max])
rf_max.fit(X_train_StandardScaler, y_train)

RandomForestRegressor(max_depth=10, min_samples_split=10, n_estimators=10,
                      random_state=1)

In [48]:

#printing the test data side by side with the predicted data
np.concatenate((y_test.values.reshape(len(y_test),1), rf_max.predict(X_test_StandardScaler).reshape(len(y_test),1)),1)

array([[0.        , 0.74114733],
       [0.        , 1.33595126],
       [0.        , 1.71571523],
       ...,
       [2.4       , 1.07692953],
       [0.        , 2.38449852],
       [0.        , 2.88757847]])

## SVR

In [51]:
kernel =['linear', 'poly', 'rbf']
gamma = ['auto', 'scale']
degree = [3,4,5,10]
C = [2.0,3.0,4.0]

In [52]:
#SVR for rainfall

#declaring parameters for SVR algorithm to determine it performance on the test data
scores_svr_rainfall= []
kernel_ = []
gamma_ =  []
degree_ = []
C_ = []



for i in kernel:
  for j in gamma:
    for k in degree:
      for l in C:
            svr_maxi = SVR(kernel = i, gamma = j, degree = k, C = l )
            svr_maxi.fit(X_train_StandardScaler, y_train)
            scores_svr_rainfall.append(mean_squared_error(y_test.values, knn_maxi.predict(X_test_StandardScaler)))

            kernel_.append(i)
            gamma_.append(j)
            degree_.append(k)
            C_.append(l)

In [53]:
#checking the minimun mean square error of the SVR algorithm used for rainfall prediction
min(scores_svr_rainfall)

28.080610717110428

In [54]:
#getting the index of the minimun mean square error of the dt algorithm from the list
index_max = np.argmin(scores_svr_rainfall)
index_max

0

In [55]:
#obtaining the parameters with the minimun mean square error of the KNN algorithm 
rainfall_svr_parameters = [kernel_[index_max], gamma_[index_max], degree_[index_max], C_[index_max]]
rainfall_svr_parameters

['linear', 'auto', 3, 2.0]

In [56]:
svr_max = SVR(kernel = kernel_[index_max], gamma = gamma_[index_max], degree = degree_[index_max], C = C_[index_max])
svr_max.fit(X_train_StandardScaler, y_train)


SVR(C=2.0, gamma='auto', kernel='linear')

In [57]:

#printing the test data side by side with the predicted data
np.concatenate((y_test.values.reshape(len(y_test),1), svr_max.predict(X_test_StandardScaler).reshape(len(y_test),1)),1)

array([[0.        , 0.10001127],
       [0.        , 0.09995554],
       [0.        , 0.09995466],
       ...,
       [2.4       , 0.10021649],
       [0.        , 0.09991968],
       [0.        , 0.10004557]])

## Model evaluation 

In [77]:
from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_error, explained_variance_score,mean_absolute_percentage_error

In [78]:
model_name = ['KNN', 'MLP', 'Decision Tree', 'Random Forest', 'SVR']
mse_value_list = [mean_squared_error(y_test, knn_max.predict(X_test_StandardScaler), squared= True),
                mean_squared_error(y_test, mlp_max.predict(X_test_StandardScaler), squared= True),
                mean_squared_error(y_test, dt_max.predict(X_test_StandardScaler), squared= True),
                mean_squared_error(y_test, rf_max.predict(X_test_StandardScaler), squared= True),
                mean_squared_error(y_test, svr_max.predict(X_test_StandardScaler), squared= True)
]

rmse_value_list=  [mean_squared_error(y_test, knn_max.predict(X_test_StandardScaler), squared= False),
                mean_squared_error(y_test, mlp_max.predict(X_test_StandardScaler), squared= False),
                mean_squared_error(y_test, dt_max.predict(X_test_StandardScaler), squared= False),
                mean_squared_error(y_test, rf_max.predict(X_test_StandardScaler), squared= False),
                mean_squared_error(y_test, svr_max.predict(X_test_StandardScaler), squared= False)
]

mae_value_list = [mean_absolute_error(y_test, knn_max.predict(X_test_StandardScaler)),
                mean_absolute_error(y_test, mlp_max.predict(X_test_StandardScaler)),
                mean_absolute_error(y_test, dt_max.predict(X_test_StandardScaler)),
                mean_absolute_error(y_test, rf_max.predict(X_test_StandardScaler)),
                mean_absolute_error(y_test, svr_max.predict(X_test_StandardScaler))
]

mape_socre_list = [mean_absolute_percentage_error(y_test, knn_max.predict(X_test_StandardScaler)),
                mean_absolute_percentage_error(y_test, mlp_max.predict(X_test_StandardScaler)),
                mean_absolute_percentage_error(y_test, dt_max.predict(X_test_StandardScaler)),
                mean_absolute_percentage_error(y_test, rf_max.predict(X_test_StandardScaler)),
                mean_absolute_percentage_error(y_test, svr_max.predict(X_test_StandardScaler))
]

r2_socre_list = [r2_score(y_test, knn_max.predict(X_test_StandardScaler)),
                r2_score(y_test, mlp_max.predict(X_test_StandardScaler)),
                r2_score(y_test, dt_max.predict(X_test_StandardScaler)),
                r2_score(y_test, rf_max.predict(X_test_StandardScaler)),
                r2_score(y_test, svr_max.predict(X_test_StandardScaler))
]

model_evl_df = pd.DataFrame({
    'Model' : model_name,
    'MSE' : mse_value_list,
    'RMSE' :rmse_value_list,
    'MAE' :mae_value_list,
    'MAPE' : mape_socre_list,
    'R^2 Score' :r2_socre_list

})




In [79]:
model_evl_df

Model        MSE      RMSE       MAE          MAPE  R^2 Score
0            KNN  27.191755  5.214571  2.315638  3.533045e+15  -0.012468
1            MLP  31.383389  5.602088  2.131122  1.059306e+15  -0.168541
2  Decision Tree  33.405779  5.779773  2.535152  3.979175e+15  -0.243843
3  Random Forest  29.798458  5.458796  2.485112  4.152694e+15  -0.109527
4            SVR  29.580129  5.438762  1.772664  2.757204e+14  -0.101398

## CV

In [107]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
def model_cv_score(model_name):
    folds = KFold(n_splits = 5, shuffle = True, random_state = 100)
    scores = cross_val_score(model_name, X_train, y_train,cv=folds)
    print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))
    return scores.mean(),scores.std()


In [108]:
model_cv_score(knn_max)


-0.05 accuracy with a standard deviation of 0.01


(-0.05019335637608413, 0.006705258588316975)

In [109]:
model_cv_score(mlp_max)

-0.24 accuracy with a standard deviation of 0.27


(-0.2445929610289616, 0.2740743799318033)

In [110]:
model_cv_score(dt_max)

-0.46 accuracy with a standard deviation of 0.33


(-0.458700919828196, 0.3336803832807382)

In [111]:
model_cv_score(rf_max)

-0.10 accuracy with a standard deviation of 0.05


(-0.10005743366803888, 0.049667834996746915)

In [112]:
model_cv_score(svr_max)

-0.11 accuracy with a standard deviation of 0.04


(-0.11453209958973778, 0.035436674130015666)

overall, KNN best fit dataset in this case

## Prediciton

In [131]:
knn_max

KNeighborsRegressor(algorithm='ball_tree', leaf_size=10, metric='chebyshev',
                    n_neighbors=25)

In [132]:
#create object

predict = pd.DataFrame({'date':pd.date_range(start="2021-03-01",end="2021-09-01")})
predict

#get columns with number value
predict['month'] = predict['date'].dt.month
predict['dayofweek']= predict['date'].dt.dayofweek+1
predict['dayofyear'] = predict['date'].dt.dayofyear
predict['year'] = predict['date'].dt.year

#order column
col = ['dayofyear','dayofweek', 'month', 'year','date']
predict = predict[col]

predict

dayofyear  dayofweek  month  year       date
0           60          1      3  2021 2021-03-01
1           61          2      3  2021 2021-03-02
2           62          3      3  2021 2021-03-03
3           63          4      3  2021 2021-03-04
4           64          5      3  2021 2021-03-05
..         ...        ...    ...   ...        ...
180        240          6      8  2021 2021-08-28
181        241          7      8  2021 2021-08-29
182        242          1      8  2021 2021-08-30
183        243          2      8  2021 2021-08-31
184        244          3      9  2021 2021-09-01

[185 rows x 5 columns]

In [133]:
X_predict = scaler.fit_transform(predict.iloc[:,:-1]) 
X_predict[:10]

array([[-1.72271354, -1.48197707, -1.46118834,  0.        ],
       [-1.70398839, -0.98258589, -1.46118834,  0.        ],
       [-1.68526324, -0.48319471, -1.46118834,  0.        ],
       [-1.6665381 ,  0.01619647, -1.46118834,  0.        ],
       [-1.64781295,  0.51558765, -1.46118834,  0.        ],
       [-1.6290878 ,  1.01497883, -1.46118834,  0.        ],
       [-1.61036266,  1.51437001, -1.46118834,  0.        ],
       [-1.59163751, -1.48197707, -1.46118834,  0.        ],
       [-1.57291236, -0.98258589, -1.46118834,  0.        ],
       [-1.55418721, -0.48319471, -1.46118834,  0.        ]])

In [134]:
predict['predict_rainfall'] = knn_max.predict(X_predict)

In [135]:
predict = predict.set_index('date')
predict


dayofyear  dayofweek  month  year  predict_rainfall
date                                                           
2021-03-01         60          1      3  2021             1.672
2021-03-02         61          2      3  2021             0.184
2021-03-03         62          3      3  2021             0.016
2021-03-04         63          4      3  2021             1.024
2021-03-05         64          5      3  2021             1.464
...               ...        ...    ...   ...               ...
2021-08-28        240          6      8  2021             1.768
2021-08-29        241          7      8  2021             2.032
2021-08-30        242          1      8  2021             0.320
2021-08-31        243          2      8  2021             0.336
2021-09-01        244          3      9  2021             0.992

[185 rows x 5 columns]

In [137]:
predict['predict_rainfall'].value_counts()


1.672    5
0.016    5
0.184    5
1.464    4
1.400    3
        ..
1.944    1
2.408    1
0.904    1
1.208    1
2.968    1
Name: predict_rainfall, Length: 140, dtype: int64

In [138]:
predict.to_csv('rainfall_predicting.csv')