In [4]:
import pandas as pd
df = pd.read_csv('dataset_with_public_holidays.csv')
df

Date  day  monthly_index        Public_Holiday  \
0     01-01-2015    4              1        Public Holiday   
1     02-01-2015    5              1  Not a public holiday   
2     03-01-2015    6              1  Not a public holiday   
3     04-01-2015    7              1  Not a public holiday   
4     05-01-2015    1              1  Not a public holiday   
...          ...  ...            ...                   ...   
2127  27-10-2020    2             10  Not a public holiday   
2128  28-10-2020    3             10  Not a public holiday   
2129  29-10-2020    4             10  Not a public holiday   
2130  30-10-2020    5             10  Not a public holiday   
2131  31-10-2020    6             10  Not a public holiday   

      Rainfall amount (millimetres)  Minimum temperature (Degree C)  \
0                               0.0                            13.3   
1                               0.0                            15.4   
2                               0.0                            20.0   
3                               4.6                            16.3   
4                               0.0                            15.0   
...                             ...                             ...   
2127                            0.0                            11.1   
2128                            0.0                             9.5   
2129                            0.0                            11.2   
2130                            0.0                            12.9   
2131                            0.0                            14.2   

      Maximum temperature (Degree C)  Daily global solar exposure (MJ/m*m)  \
0                               26.9                                  23.6   
1                               38.8                                  26.8   
2                               38.2                                  26.5   
3                               21.4                                  25.2   
4                               22.0                                  30.7   
...                              ...                                   ...   
2127                            19.6                                  20.1   
2128                            20.9                                  26.7   
2129                            24.3                                  17.1   
2130                            18.6                                  21.0   
2131                            16.8                                  10.0   

      Total_Pedestrian_Count_per_day  
0                             471563  
1                             389048  
2                             291761  
3                             382364  
4                             487220  
...                              ...  
2127                          177267  
2128                          311278  
2129                          263334  
2130                          313225  
2131                          370181  

[2132 rows x 9 columns]

In [5]:
X = df.iloc[:,1:-1]
Y = df['Total_Pedestrian_Count_per_day']
X = X.fillna(X.mean())
X

day  monthly_index        Public_Holiday  Rainfall amount (millimetres)  \
0       4              1        Public Holiday                            0.0   
1       5              1  Not a public holiday                            0.0   
2       6              1  Not a public holiday                            0.0   
3       7              1  Not a public holiday                            4.6   
4       1              1  Not a public holiday                            0.0   
...   ...            ...                   ...                            ...   
2127    2             10  Not a public holiday                            0.0   
2128    3             10  Not a public holiday                            0.0   
2129    4             10  Not a public holiday                            0.0   
2130    5             10  Not a public holiday                            0.0   
2131    6             10  Not a public holiday                            0.0   

      Minimum temperature (Degree C)  Maximum temperature (Degree C)  \
0                               13.3                            26.9   
1                               15.4                            38.8   
2                               20.0                            38.2   
3                               16.3                            21.4   
4                               15.0                            22.0   
...                              ...                             ...   
2127                            11.1                            19.6   
2128                             9.5                            20.9   
2129                            11.2                            24.3   
2130                            12.9                            18.6   
2131                            14.2                            16.8   

      Daily global solar exposure (MJ/m*m)  
0                                     23.6  
1                                     26.8  
2                                     26.5  
3                                     25.2  
4                                     30.7  
...                                    ...  
2127                                  20.1  
2128                                  26.7  
2129                                  17.1  
2130                                  21.0  
2131                                  10.0  

[2132 rows x 7 columns]

In [6]:
rng = pd.date_range('2020-11-01', periods=61, freq='D')
X_test = pd.DataFrame({ 'Date': rng}) 
X_test['Date'] = X_test['Date'].astype('datetime64[ns]')
X_test

Date
0  2020-11-01
1  2020-11-02
2  2020-11-03
3  2020-11-04
4  2020-11-05
..        ...
56 2020-12-27
57 2020-12-28
58 2020-12-29
59 2020-12-30
60 2020-12-31

[61 rows x 1 columns]

In [7]:
# Loading the weather test dataset 
test_dataset = pd.read_csv('Test_dataset_updated.csv') 
test_dataset

Date   Rainfall   Solar Exposure  Minimum temperature  \
0   01-11-2020        0.0            23.2                 12.6   
1   02-11-2020        0.0            26.8                  9.6   
2   03-11-2020        0.0            26.9                 12.1   
3   04-11-2020        0.0             5.5                 21.9   
4   05-11-2020        2.8            23.1                 11.1   
..         ...        ...             ...                  ...   
56  27-12-2020        0.0             3.3                 16.2   
57  28-12-2020        3.2            26.5                 11.5   
58  29-12-2020        0.0            30.7                  9.0   
59  30-12-2020        0.0            30.3                 13.7   
60  31-12-2020        0.0             7.3                 15.5   

    Maximum Temperature  
0                  17.0  
1                  29.5  
2                  30.4  
3                  22.8  
4                  15.8  
..                  ...  
56                 31.9  
57                 17.8  
58                 21.3  
59                 21.4  
60                 21.2  

[61 rows x 5 columns]

In [8]:
public = pd.read_csv('Public_Holiday_test_set.csv')
holidays = public[['Holiday']]
holidays['Holiday'] = holidays['Holiday'].astype('datetime64[ns]')
holidays['Public_Holiday'] = 'Public Holiday'

X_test = X_test.set_index('Date').join(holidays.set_index("Holiday"), how='left')
X_test['Public_Holiday'].fillna('Not a public holiday', inplace=True)
X_test

Public_Holiday
2020-11-01  Not a public holiday
2020-11-02  Not a public holiday
2020-11-03        Public Holiday
2020-11-04  Not a public holiday
2020-11-05  Not a public holiday
...                          ...
2020-12-27  Not a public holiday
2020-12-28        Public Holiday
2020-12-29  Not a public holiday
2020-12-30  Not a public holiday
2020-12-31  Not a public holiday

[61 rows x 1 columns]

In [9]:
X_test['day'] = X_test.index.dayofweek + 1
X_test['monthly_index'] = X_test.index.month

X_test['Rainfall amount (millimetres)'] = test_dataset['Rainfall '].values
X_test['Minimum temperature (Degree C)'] = test_dataset['Minimum temperature'].values
X_test['Maximum temperature (Degree C)'] = test_dataset['Maximum Temperature'].values
X_test['Daily global solar exposure (MJ/m*m)'] = test_dataset['Solar Exposure'].values

X_test

Public_Holiday  day  monthly_index  \
2020-11-01  Not a public holiday    7             11   
2020-11-02  Not a public holiday    1             11   
2020-11-03        Public Holiday    2             11   
2020-11-04  Not a public holiday    3             11   
2020-11-05  Not a public holiday    4             11   
...                          ...  ...            ...   
2020-12-27  Not a public holiday    7             12   
2020-12-28        Public Holiday    1             12   
2020-12-29  Not a public holiday    2             12   
2020-12-30  Not a public holiday    3             12   
2020-12-31  Not a public holiday    4             12   

            Rainfall amount (millimetres)  Minimum temperature (Degree C)  \
2020-11-01                            0.0                            12.6   
2020-11-02                            0.0                             9.6   
2020-11-03                            0.0                            12.1   
2020-11-04                            0.0                            21.9   
2020-11-05                            2.8                            11.1   
...                                   ...                             ...   
2020-12-27                            0.0                            16.2   
2020-12-28                            3.2                            11.5   
2020-12-29                            0.0                             9.0   
2020-12-30                            0.0                            13.7   
2020-12-31                            0.0                            15.5   

            Maximum temperature (Degree C)  \
2020-11-01                            17.0   
2020-11-02                            29.5   
2020-11-03                            30.4   
2020-11-04                            22.8   
2020-11-05                            15.8   
...                                    ...   
2020-12-27                            31.9   
2020-12-28                            17.8   
2020-12-29                            21.3   
2020-12-30                            21.4   
2020-12-31                            21.2   

            Daily global solar exposure (MJ/m*m)  
2020-11-01                                  23.2  
2020-11-02                                  26.8  
2020-11-03                                  26.9  
2020-11-04                                   5.5  
2020-11-05                                  23.1  
...                                          ...  
2020-12-27                                   3.3  
2020-12-28                                  26.5  
2020-12-29                                  30.7  
2020-12-30                                  30.3  
2020-12-31                                   7.3  

[61 rows x 7 columns]

In [10]:
X = X.fillna(X.mean())


combined = pd.concat([X, X_test])
combined.Public_Holiday = pd.Categorical(combined.Public_Holiday)
combined['holiday_code'] = combined.Public_Holiday.cat.codes
combined.drop(columns=['Public_Holiday'], inplace = True)

X = combined[:len(X)]
X_test = combined[len(X):]

X_test

day  monthly_index  Rainfall amount (millimetres)  \
2020-11-01    7             11                            0.0   
2020-11-02    1             11                            0.0   
2020-11-03    2             11                            0.0   
2020-11-04    3             11                            0.0   
2020-11-05    4             11                            2.8   
...         ...            ...                            ...   
2020-12-27    7             12                            0.0   
2020-12-28    1             12                            3.2   
2020-12-29    2             12                            0.0   
2020-12-30    3             12                            0.0   
2020-12-31    4             12                            0.0   

            Minimum temperature (Degree C)  Maximum temperature (Degree C)  \
2020-11-01                            12.6                            17.0   
2020-11-02                             9.6                            29.5   
2020-11-03                            12.1                            30.4   
2020-11-04                            21.9                            22.8   
2020-11-05                            11.1                            15.8   
...                                    ...                             ...   
2020-12-27                            16.2                            31.9   
2020-12-28                            11.5                            17.8   
2020-12-29                             9.0                            21.3   
2020-12-30                            13.7                            21.4   
2020-12-31                            15.5                            21.2   

            Daily global solar exposure (MJ/m*m)  holiday_code  
2020-11-01                                  23.2             0  
2020-11-02                                  26.8             0  
2020-11-03                                  26.9             1  
2020-11-04                                   5.5             0  
2020-11-05                                  23.1             0  
...                                          ...           ...  
2020-12-27                                   3.3             0  
2020-12-28                                  26.5             1  
2020-12-29                                  30.7             0  
2020-12-30                                  30.3             0  
2020-12-31                                   7.3             0  

[61 rows x 7 columns]

In [11]:
from sklearn.preprocessing import StandardScaler
newscaler = StandardScaler()
X_scaled = newscaler.fit_transform(X) 
X_test_scaled = newscaler.fit_transform(X_test) 
X_scaled

array([[-9.38637205e-04, -1.58631120e+00, -3.70860268e-01, ...,
         1.03952738e+00,  1.11446043e+00,  5.09777812e+00],
       [ 4.99354993e-01, -1.58631120e+00, -3.70860268e-01, ...,
         2.94037146e+00,  1.51837475e+00, -1.96163893e-01],
       [ 9.99648624e-01, -1.58631120e+00, -3.70860268e-01, ...,
         2.84453058e+00,  1.48050778e+00, -1.96163893e-01],
       ...,
       [-9.38637205e-04,  1.06833203e+00, -3.70860268e-01, ...,
         6.24216911e-01,  2.94009485e-01, -1.96163893e-01],
       [ 4.99354993e-01,  1.06833203e+00, -3.70860268e-01, ...,
        -2.86271427e-01,  7.86280055e-01, -1.96163893e-01],
       [ 9.99648624e-01,  1.06833203e+00, -3.70860268e-01, ...,
        -5.73794061e-01, -6.02175399e-01, -1.96163893e-01]])

In [12]:
new_results_df_per_day = pd.read_csv('new_results_df_per_day.csv') 
new_results_df_per_day

Unnamed: 0        date  Total_Pedestrian_Count_per_day
0              0  2015-01-01                          471563
1              1  2015-01-02                          389048
2              2  2015-01-03                          291761
3              3  2015-01-04                          382364
4              4  2015-01-05                          487220
...          ...         ...                             ...
2187        2187  2020-12-27                          385422
2188        2188  2020-12-28                          473046
2189        2189  2020-12-29                          497027
2190        2190  2020-12-30                          467634
2191        2191  2020-12-31                          472586

[2192 rows x 3 columns]

In [13]:
realY = new_results_df_per_day['Total_Pedestrian_Count_per_day'].iloc[-61:]

## KNN

In [14]:

from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
scores = []
neighbor = []
leaf_size = []
metric = []
weight = []
algorithm = []

n_neighbors = [2,3,4,5,6,7,8,9]
leaf_sizes = [10,20,30,50,100,500]
metrics = ['euclidean','chebyshev','manhattan']
weights = ['uniform', 'distance']
algorithms = ['auto', 'ball_tree', 'kd_tree', 'brute'] 

for i in n_neighbors:
  for j in leaf_sizes:
    for k in metrics:
      for l in weights:
        for m in algorithms:
          knn = KNeighborsRegressor(n_neighbors = i, leaf_size = j, metric = k, weights = l, algorithm = m)
          knn.fit(X_scaled, Y)
          scores.append(mean_squared_error(realY, knn.predict(X_test_scaled)))
          neighbor.append(i)
          leaf_size.append(j)
          metric.append(k)
          weight.append(l)
          algorithm.append(m)

In [15]:
min(scores)
import numpy as np
index = np.argmin(scores)
parameters = [neighbor[index], leaf_size[index], metric[index], weight[index], algorithm[index]]
parameters

[6, 10, 'manhattan', 'distance', 'auto']

In [16]:
knn_min = KNeighborsRegressor(n_neighbors = 6, leaf_size = 10, metric = 'manhattan', weights = 'distance', algorithm = 'auto')
knn_min.fit(X_scaled, Y)
Y_pred_knn = knn_min.predict(X_test_scaled)
print(
    np.concatenate((
        realY.values.reshape(len(realY),1), 
        Y_pred_knn.reshape(len(Y_pred_knn),1)
),1))

[[339667.         459667.96555429]
 [335642.         704420.55008969]
 [286980.         595268.45662122]
 [190675.         628759.86066333]
 [246692.         487559.92517591]
 [288551.         636198.6795056 ]
 [365548.         526386.8431199 ]
 [321671.         474645.05467835]
 [262820.         655214.17955375]
 [264765.         689842.57413073]
 [224537.         604084.61411684]
 [287179.         718199.45604958]
 [330106.         526209.74502305]
 [436497.         505105.38364594]
 [300190.         635856.71298117]
 [257361.         690260.82170979]
 [287853.         596871.15355293]
 [313407.         756635.31670842]
 [300283.         716713.57828862]
 [397150.         751657.17803946]
 [489118.         717505.91119538]
 [309849.         640799.11492241]
 [261242.         490539.34821066]
 [316024.         515438.19331956]
 [340384.         748893.4297231 ]
 [353597.         657218.26156485]
 [456912.         740938.87145997]
 [481376.         573191.28932093]
 [358501.         46

SVM

In [17]:
from sklearn.svm import SVR
scores = []
kernel = []
gamma = []
C = []
degree = []

kernels = ['linear', 'rbf']
gammas = [0.1, 1, 10, 100]
Cs = [0.1, 1, 10, 100]
degrees = [0, 1, 2, 3, 4, 5, 6]


for i in kernels:
  for j in gammas:
    for k in Cs:
        for l in degrees: 
          svm = SVR(kernel=i, gamma=j, C=k, degree=l)
          svm.fit(X_scaled, Y)
          scores.append(mean_squared_error(realY, svm.predict(X_test_scaled)))
          kernel.append(i)
          gamma.append(j)
          C.append(k)
          degree.append(l)


In [18]:
index = np.argmin(scores)
parameters = [kernel[index], gamma[index], C[index], degree[index]]
parameters

['linear', 0.1, 100, 0]

In [20]:
svm_min = SVR(kernel='linear', gamma=0.1, C=100, degree=0)
svm_min.fit(X_scaled, Y)
Y_pred_svm = svm_min.predict(X_test_scaled)
print(
    np.concatenate((
        realY.values.reshape(len(realY),1), 
        Y_pred_svm.reshape(len(Y_pred_svm),1)
),1))

[[339667.         586982.78519841]
 [335642.         649177.44932603]
 [286980.         612473.82377984]
 [190675.         620965.93201419]
 [246692.         601626.92548276]
 [288551.         580267.32123854]
 [365548.         588495.80994919]
 [321671.         589778.25367785]
 [262820.         654829.29441188]
 [264765.         663056.56973486]
 [224537.         633015.18070337]
 [287179.         630386.62190456]
 [330106.         606981.2095484 ]
 [436497.         604376.32102995]
 [300190.         598982.80367629]
 [257361.         663528.28083278]
 [287853.         636151.70871347]
 [313407.         641861.03315557]
 [300283.         652239.09154053]
 [397150.         621891.83848751]
 [489118.         603496.97529097]
 [309849.         593717.80229261]
 [261242.         605981.13650345]
 [316024.         622943.03467688]
 [340384.         647659.04699007]
 [353597.         624207.14254444]
 [456912.         634583.57407405]
 [481376.         589637.94603239]
 [358501.         58

In [21]:
from sklearn.tree import DecisionTreeRegressor
scores
# Decision Tree
scores = []
splitter = []
criterion =  []
max_depth = []
max_feature = []
min_samples_split = []

splitters =['best','random']
criterions = ['mse', 'friedman_mse', 'mae']
max_depths = [1,2,3,4,5,10,20,30,40]
max_features =['auto','sqrt','log2'] 
min_samples_splits = [2,3,4,5,10,20,30,40]

for i in splitters:
  for j in criterions:
    for k in max_depths:
      for l in max_features:
        for m in min_samples_splits:
            tree = DecisionTreeRegressor(splitter = i, criterion = j, max_depth = k, max_features = l, min_samples_split = m)
            tree.fit(X_scaled, Y)
            scores.append(mean_squared_error(realY, tree.predict(X_test_scaled)))

            splitter.append(i)
            criterion.append(j)
            max_depth.append(k)
            max_feature.append(l)
            min_samples_split.append(m)

In [22]:
index = np.argmin(scores)
parameters = [splitter[index], criterion[index], max_depth[index], max_feature[index], min_samples_split[index]]
parameters

['best', 'mse', 20, 'sqrt', 40]

In [23]:
tree_min = DecisionTreeRegressor(splitter = 'best', criterion = 'mse', max_depth = 2, max_features = 'sqrt', min_samples_split = 3)
tree_min.fit(X_scaled, Y)
Y_pred_tree = tree_min.predict(X_test_scaled)
print(
    np.concatenate((
        realY.values.reshape(len(realY),1), 
        Y_pred_tree.reshape(len(Y_pred_tree),1)
),1))

[[339667.         631451.40710383]
 [335642.         631451.40710383]
 [286980.         631451.40710383]
 [190675.         577992.59591837]
 [246692.         631451.40710383]
 [288551.         577992.59591837]
 [365548.         631451.40710383]
 [321671.         631451.40710383]
 [262820.         631451.40710383]
 [264765.         631451.40710383]
 [224537.         577992.59591837]
 [287179.         577992.59591837]
 [330106.         577992.59591837]
 [436497.         631451.40710383]
 [300190.         451168.81818182]
 [257361.         631451.40710383]
 [287853.         631451.40710383]
 [313407.         631451.40710383]
 [300283.         631451.40710383]
 [397150.         631451.40710383]
 [489118.         577992.59591837]
 [309849.         451168.81818182]
 [261242.         577992.59591837]
 [316024.         577992.59591837]
 [340384.         631451.40710383]
 [353597.         631451.40710383]
 [456912.         631451.40710383]
 [481376.         577992.59591837]
 [358501.         45

In [24]:
from sklearn.ensemble import RandomForestRegressor
# Random forest
scores = []
n_estimator = []
criterion =  []
max_depth = []
max_feature = []
min_samples_split = []


criterions = ['mse', 'friedman_mse']
max_depths = [10,20,30,40]
max_features =['auto','sqrt','log2'] 
min_samples_splits = [10,20,30,40]
n_estimators =[10,50,100]


for i in n_estimators:
  for j in criterions:
    for k in max_depths:
      for l in max_features:
        for m in min_samples_splits:
            rf = RandomForestRegressor(n_estimators = i, criterion = j, max_depth = k, max_features = l, min_samples_split = m)
            rf.fit(X_scaled, Y)
            scores.append(mean_squared_error(realY, rf.predict(X_test_scaled)))

            n_estimator.append(i)
            criterion.append(j)
            max_depth.append(k)
            max_feature.append(l)
            min_samples_split.append(m)

In [25]:
index = np.argmin(scores)
parameters = [n_estimator[index], criterion[index], max_depth[index], max_feature[index], min_samples_split[index]]
parameters

[10, 'mse', 40, 'auto', 30]

In [26]:
rf_min = RandomForestRegressor(n_estimators = 10, criterion = 'mse', max_depth = 40, max_features = 'log2', min_samples_split = 20)
rf_min.fit(X_scaled, Y)
Y_pred_rf = rf_min.predict(X_test_scaled)
print(
    np.concatenate((
        realY.values.reshape(len(realY),1), 
        Y_pred_rf.reshape(len(Y_pred_rf),1)
),1))

[[339667.         461589.38943962]
 [335642.         623424.11153805]
 [286980.         638898.26605866]
 [190675.         643049.13281455]
 [246692.         638239.5569076 ]
 [288551.         585085.09103051]
 [365548.         514607.20986217]
 [321671.         471949.49383642]
 [262820.         632962.71627489]
 [264765.         688642.6362069 ]
 [224537.         639269.22787879]
 [287179.         558886.04341677]
 [330106.         702067.38247154]
 [436497.         560999.35693105]
 [300190.         526563.7633555 ]
 [257361.         650049.36864783]
 [287853.         609441.82216192]
 [313407.         666146.70752137]
 [300283.         705510.48788439]
 [397150.         737600.24325318]
 [489118.         650296.08089444]
 [309849.         535068.85326277]
 [261242.         468079.77516268]
 [316024.         500960.05490555]
 [340384.         679943.62353483]
 [353597.         593975.75915621]
 [456912.         681744.16428504]
 [481376.         560014.03686044]
 [358501.         33

In [33]:
from sklearn.neural_network import MLPRegressor

scores = []
hidden_layer_size = []
solver = []
activation = []
alpha = []
learning_rate = []

hidden_layer_sizes = []
for i in range(1,10):
  hidden_layer_sizes.append(((i,i,i)))
activations = ['tanh', 'relu', 'logistic']
solvers = ['lbfgs', 'sgd', 'adam']
alphas = [0.0001, 0.05, 0.01, .001]
learning_rates = ['constant','adaptive', 'invscaling']

for i in hidden_layer_sizes:
  for j in activations:
    print(i, j)
    for k in solvers:
      for l in alphas:
        for m in learning_rates:
          nn = MLPRegressor(hidden_layer_sizes = i, activation = j, solver = k, alpha = l, learning_rate = m)
          nn.fit(X_scaled, Y)
          scores.append(mean_squared_error(realY, nn.predict(X_test_scaled)))

          hidden_layer_size.append(i)
          activation.append(j)
          solver.append(k)
          alpha.append(l)
          learning_rate.append(m)

(1, 1, 1) tanh
(1, 1, 1) relu
(1, 1, 1) logistic
(2, 2, 2) tanh
(2, 2, 2) relu
(2, 2, 2) logistic
(3, 3, 3) tanh
(3, 3, 3) relu
(3, 3, 3) logistic
(4, 4, 4) tanh
(4, 4, 4) relu
(4, 4, 4) logistic
(5, 5, 5) tanh
(5, 5, 5) relu
(5, 5, 5) logistic
(6, 6, 6) tanh
(6, 6, 6) relu
(6, 6, 6) logistic
(7, 7, 7) tanh
(7, 7, 7) relu
(7, 7, 7) logistic
(8, 8, 8) tanh
(8, 8, 8) relu
(8, 8, 8) logistic
(9, 9, 9) tanh
(9, 9, 9) relu
(9, 9, 9) logistic


In [37]:
index = np.argmin(scores)
parameters = [hidden_layer_size[index], activation[index], solver[index], alpha[index], learning_rate[index]]
parameters

[(4, 4, 4), 'tanh', 'sgd', 0.0001, 'invscaling']

In [38]:
nn_min = MLPRegressor(hidden_layer_sizes = (4,4,4), activation = 'tanh', solver = 'sgd', alpha = 0.0001, learning_rate = 'invscaling')
nn_min.fit(X_scaled, Y)
Y_pred_nn = nn_min.predict(X_test_scaled)
print(
    np.concatenate((
        realY.values.reshape(len(realY),1), 
        Y_pred_nn.reshape(len(Y_pred_nn),1)
),1))

[[339667.         372816.53165363]
 [335642.         372816.53165363]
 [286980.         372816.53165363]
 [190675.         372816.53165363]
 [246692.         372816.53165363]
 [288551.         372816.53165363]
 [365548.         372816.53165363]
 [321671.         372816.53165363]
 [262820.         372816.53165363]
 [264765.         372816.53165363]
 [224537.         372816.53165363]
 [287179.         372816.53165363]
 [330106.         372816.53165363]
 [436497.         372816.53165363]
 [300190.         372816.53165363]
 [257361.         372816.53165363]
 [287853.         372816.53165363]
 [313407.         372816.53165363]
 [300283.         372816.53165363]
 [397150.         372816.53165363]
 [489118.         372816.53165363]
 [309849.         372816.53165363]
 [261242.         372816.53165363]
 [316024.         372816.53165363]
 [340384.         372816.53165363]
 [353597.         372816.53165363]
 [456912.         372816.53165363]
 [481376.         372816.53165363]
 [358501.         37

In [39]:
from prettytable import PrettyTable
from sklearn.metrics import r2_score
rt = PrettyTable(["Algorithm", "r2"])
rt.align["Algorithm"] = "l" # Left align city names
rt.padding_width = 1 # One space between column edges and contents (default)
rt.add_row(["KNN",
            '{:.2f}'.format(r2_score(realY, Y_pred_knn))])
rt.add_row(["SVM",
            '{:.2f}'.format(r2_score(realY, Y_pred_svm))])
rt.add_row(["Decision Tree",
            '{:.2f}'.format(r2_score(realY, Y_pred_tree))])
rt.add_row(["Random Forest",
            '{:.2f}'.format(r2_score(realY, Y_pred_rf))])
rt.add_row(["SVR",
            '{:.2f}'.format(r2_score(realY, Y_pred_nn))])
print(rt)

+---------------+-------+
| Algorithm     |   r2  |
+---------------+-------+
| KNN           | -5.36 |
| SVM           | -5.45 |
| Decision Tree | -4.42 |
| Random Forest | -4.60 |
| SVR           | -0.04 |
+---------------+-------+


In [40]:
#save the best model
import pickle
pickle.dump(tree_min, open('Model/pedestriant_ml_prediction_model', 'wb'))