In [63]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
import numpy as np
import pandas as pd
from pandas import DataFrame as df, Series as se
from datetime import datetime, timedelta

In [38]:
dataset_wt_weather_features = pd.read_csv('dataset_wt_weather_features.csv')

In [39]:
dataset_wt_weather_features

date  ...  Total_Pedestrian_Count_per_day
0     2015-01-01 00:00:00  ...                          471563
1     2015-01-02 00:00:00  ...                          389048
2     2015-01-03 00:00:00  ...                          291761
3     2015-01-04 00:00:00  ...                          382364
4     2015-01-05 00:00:00  ...                          487220
...                   ...  ...                             ...
2126  2020-10-27 00:00:00  ...                          177267
2127  2020-10-28 00:00:00  ...                          311278
2128  2020-10-29 00:00:00  ...                          263334
2129  2020-10-30 00:00:00  ...                          313225
2130  2020-10-31 00:00:00  ...                          370181

[2131 rows x 6 columns]

In [40]:
dataset_wt_weather_features['Date'] = dataset_wt_weather_features['date'].astype('datetime64[ns]')

In [41]:
import numpy
dataset = numpy.zeros(shape=(2193,6))

In [42]:
dataset = df(train_data)

In [43]:
dataset.rename(columns = {0:'Year',1:'day_of_year',2:'monthly_index',3:'day_of_week',4:'Minimum temperature (Degree C)',	5:'Maximum temperature (Degree C)' },inplace = True)

In [44]:
from datetime import datetime, timedelta
#generating the test data set
base = datetime.strptime('2015-01-01', '%Y-%m-%d')
date_list = [base + timedelta(days=x) for x in range(2192)]
dataset = df(date_list)
#renaming a column 
dataset.rename(columns = {0:'Date'},inplace = True)
#Incorporating the monthly index. Representing January as 1 and December as 12.
dataset['monthly_index'] = dataset.Date.dt.month

#Incorporating the year
dataset['Year'] = dataset.Date.dt.year

#Incorporating the weekly index. Representing monday as 1 and sunday as 7.
dataset['day_of_week'] = dataset.Date.dt.dayofweek + 1

#Incorporating the day of the year
dataset['day_of_year'] = dataset.Date.dt.dayofyear

#rearranging columns for the test dataset
dataset = dataset[['Year', 'day_of_year', 'monthly_index','day_of_week' ]]

#displaying the test dataset
dataset

Year  day_of_year  monthly_index  day_of_week
0     2015            1              1            4
1     2015            2              1            5
2     2015            3              1            6
3     2015            4              1            7
4     2015            5              1            1
...    ...          ...            ...          ...
2187  2020          362             12            7
2188  2020          363             12            1
2189  2020          364             12            2
2190  2020          365             12            3
2191  2020          366             12            4

[2192 rows x 4 columns]

In [45]:
from datetime import datetime, timedelta
dataset['Minimum temperature (Degree C)'] = dataset_wt_weather_features['Minimum temperature (Degree C)']
dataset['Maximum temperature (Degree C)'] = dataset_wt_weather_features['Maximum temperature (Degree C)']



In [46]:
dataset

Year  ...  Maximum temperature (Degree C)
0     2015  ...                            26.9
1     2015  ...                            38.8
2     2015  ...                            38.2
3     2015  ...                            21.4
4     2015  ...                            22.0
...    ...  ...                             ...
2187  2020  ...                             NaN
2188  2020  ...                             NaN
2189  2020  ...                             NaN
2190  2020  ...                             NaN
2191  2020  ...                             NaN

[2192 rows x 6 columns]

In [47]:
dataset.isnull().sum()

Year                               0
day_of_year                        0
monthly_index                      0
day_of_week                        0
Minimum temperature (Degree C)    61
Maximum temperature (Degree C)    61
dtype: int64

In [48]:
dataset[2131:2192] 


Year  ...  Maximum temperature (Degree C)
2131  2020  ...                             NaN
2132  2020  ...                             NaN
2133  2020  ...                             NaN
2134  2020  ...                             NaN
2135  2020  ...                             NaN
...    ...  ...                             ...
2187  2020  ...                             NaN
2188  2020  ...                             NaN
2189  2020  ...                             NaN
2190  2020  ...                             NaN
2191  2020  ...                             NaN

[61 rows x 6 columns]

In [49]:
Test_dataset = pd.read_csv('Test_dataset_updated.csv')
Test_dataset['Minimum temperature']

0     12.6
1      9.6
2     12.1
3     21.9
4     11.1
      ... 
56    16.2
57    11.5
58     9.0
59    13.7
60    15.5
Name: Minimum temperature, Length: 61, dtype: float64

In [50]:
dataset ['Minimum temperature (Degree C)'][2131:2192] = Test_dataset_updated['Minimum temperature']
dataset ['Maximum temperature (Degree C)'][2131:2192] = Test_dataset_updated['Maximum Temperature']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [51]:
dataset

Year  ...  Maximum temperature (Degree C)
0     2015  ...                            26.9
1     2015  ...                            38.8
2     2015  ...                            38.2
3     2015  ...                            21.4
4     2015  ...                            22.0
...    ...  ...                             ...
2187  2020  ...                            31.9
2188  2020  ...                            17.8
2189  2020  ...                            21.3
2190  2020  ...                            21.4
2191  2020  ...                            21.2

[2192 rows x 6 columns]

In [52]:
X_train = dataset[['Year', 'day_of_year', 'monthly_index','day_of_week' ]]
X_train

Year  day_of_year  monthly_index  day_of_week
0     2015            1              1            4
1     2015            2              1            5
2     2015            3              1            6
3     2015            4              1            7
4     2015            5              1            1
...    ...          ...            ...          ...
2187  2020          362             12            7
2188  2020          363             12            1
2189  2020          364             12            2
2190  2020          365             12            3
2191  2020          366             12            4

[2192 rows x 4 columns]

In [59]:
Y_train_min_temp =  dataset['Minimum temperature (Degree C)']
Y_train_max_temp = dataset['Maximum temperature (Degree C)']

In [53]:
from datetime import datetime, timedelta
#generating the test data set
base = datetime.strptime('2021-01-01', '%Y-%m-%d')
date_list = [base + timedelta(days=x) for x in range(90)]
X_test = df(date_list)
#renaming a column 
X_test.rename(columns = {0:'Date'},inplace = True)
#Incorporating the monthly index. Representing January as 1 and December as 12.
X_test['monthly_index'] = X_test.Date.dt.month

#Incorporating the year
X_test['Year'] = X_test.Date.dt.year

#Incorporating the weekly index. Representing monday as 1 and sunday as 7.
X_test['day_of_week'] = X_test.Date.dt.dayofweek + 1

#Incorporating the day of the year
X_test['day_of_year'] = X_test.Date.dt.dayofyear

#rearranging columns for the test dataset
X_test = X_test[['Year', 'day_of_year', 'monthly_index','day_of_week' ]]

#displaying the test dataset
X_test

Year  day_of_year  monthly_index  day_of_week
0   2021            1              1            5
1   2021            2              1            6
2   2021            3              1            7
3   2021            4              1            1
4   2021            5              1            2
..   ...          ...            ...          ...
85  2021           86              3            6
86  2021           87              3            7
87  2021           88              3            1
88  2021           89              3            2
89  2021           90              3            3

[90 rows x 4 columns]

In [54]:
X_test

Year  day_of_year  monthly_index  day_of_week
0   2021            1              1            5
1   2021            2              1            6
2   2021            3              1            7
3   2021            4              1            1
4   2021            5              1            2
..   ...          ...            ...          ...
85  2021           86              3            6
86  2021           87              3            7
87  2021           88              3            1
88  2021           89              3            2
89  2021           90              3            3

[90 rows x 4 columns]

In [57]:
from sklearn.preprocessing import StandardScaler

#using standard scaler
scaler = StandardScaler()
#fit get the mean and standard deviation of the train features 
#while tranform applies the standardation formular
X_train_StandardScaler = scaler.fit_transform(X_train) 
X_train_StandardScaler

array([[-1.46381204, -1.72731051, -1.60102055,  0.        ],
       [-1.46381204, -1.7178285 , -1.60102055,  0.50011409],
       [-1.46381204, -1.70834648, -1.60102055,  1.00022818],
       ...,
       [ 1.4632779 ,  1.71466206,  1.58832244, -1.00022818],
       [ 1.4632779 ,  1.72414407,  1.58832244, -0.50011409],
       [ 1.4632779 ,  1.73362609,  1.58832244,  0.        ]])

In [58]:
#using standard scaler
scaler_test = StandardScaler()
#fit get the mean and standard deviation of the train features 
#while tranform applies the standardation formular
X_test_StandardScaler = scaler_test.fit_transform(X_test) 
X_test_StandardScaler

array([[ 0.        , -1.71291154, -1.20482899,  0.49724516],
       [ 0.        , -1.67441914, -1.20482899,  0.99449032],
       [ 0.        , -1.63592675, -1.20482899,  1.49173547],
       [ 0.        , -1.59743435, -1.20482899, -1.49173547],
       [ 0.        , -1.55894196, -1.20482899, -0.99449032],
       [ 0.        , -1.52044957, -1.20482899, -0.49724516],
       [ 0.        , -1.48195717, -1.20482899,  0.        ],
       [ 0.        , -1.44346478, -1.20482899,  0.49724516],
       [ 0.        , -1.40497238, -1.20482899,  0.99449032],
       [ 0.        , -1.36647999, -1.20482899,  1.49173547],
       [ 0.        , -1.3279876 , -1.20482899, -1.49173547],
       [ 0.        , -1.2894952 , -1.20482899, -0.99449032],
       [ 0.        , -1.25100281, -1.20482899, -0.49724516],
       [ 0.        , -1.21251041, -1.20482899,  0.        ],
       [ 0.        , -1.17401802, -1.20482899,  0.49724516],
       [ 0.        , -1.13552563, -1.20482899,  0.99449032],
       [ 0.        , -1.

In [60]:
svr_min =  SVR(kernel = 'linear', gamma = 'auto', degree = 3, C = 2.0)
svr_min.fit(X_train_StandardScaler, Y_train_min_temp)

SVR(C=2.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
    kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [70]:
test_min_temp = svr_min.predict(X_test_StandardScaler)

In [73]:
test_min_temp

array([13.38308442, 13.4191009 , 13.45511738, 13.09212765, 13.12814413,
       13.16416061, 13.20017709, 13.23619357, 13.27221005, 13.30822653,
       12.9452368 , 12.98125328, 13.01726976, 13.05328624, 13.08930272,
       13.1253192 , 13.16133568, 12.79834595, 12.83436243, 12.87037891,
       12.90639539, 12.94241187, 12.97842835, 13.01444483, 12.65145511,
       12.68747159, 12.72348807, 12.75950455, 12.79552103, 12.83153751,
       12.86755399, 11.46716637, 11.50318285, 11.53919933, 11.57521581,
       11.61123229, 11.64724877, 11.68326525, 11.32027552, 11.356292  ,
       11.39230848, 11.42832496, 11.46434144, 11.50035792, 11.5363744 ,
       11.17338468, 11.20940116, 11.24541764, 11.28143412, 11.3174506 ,
       11.35346708, 11.38948356, 11.02649383, 11.06251031, 11.09852679,
       11.13454327, 11.17055975, 11.20657623, 11.24259271,  9.84220509,
        9.87822157,  9.91423805,  9.95025453,  9.98627101, 10.02228749,
       10.05830397,  9.69531425,  9.73133073,  9.76734721,  9.80

In [64]:
#obtaining the parameters with the minimun mean square error of the KNN algorithm 
knn_max = KNeighborsRegressor(n_neighbors = 25, leaf_size = 10,  metric = 'manhattan', weights = 'uniform', algorithm = 'auto')
knn_max.fit(X_train_StandardScaler, Y_train_max_temp)

KNeighborsRegressor(algorithm='auto', leaf_size=10, metric='manhattan',
                    metric_params=None, n_jobs=None, n_neighbors=25, p=2,
                    weights='uniform')

In [74]:
test_max_temp = knn_max.predict(X_test_StandardScaler)

In [75]:
test_max_temp

array([26.456, 28.252, 25.808, 25.612, 25.708, 26.952, 26.484, 26.636,
       27.312, 25.924, 26.26 , 25.792, 27.568, 26.036, 24.924, 27.028,
       25.756, 25.428, 26.108, 27.312, 25.084, 23.992, 25.604, 23.452,
       23.572, 24.944, 26.608, 24.424, 23.444, 24.236, 22.372, 16.028,
       15.74 , 15.492, 15.552, 15.284, 15.228, 14.984, 15.32 , 15.344,
       15.116, 15.052, 14.388, 14.14 , 14.22 , 14.36 , 14.928, 14.644,
       14.684, 14.82 , 14.648, 14.984, 14.36 , 14.924, 15.036, 14.808,
       14.988, 14.528, 14.58 , 20.732, 20.484, 20.188, 20.316, 20.548,
       18.972, 19.752, 22.044, 22.288, 21.108, 21.472, 21.216, 21.104,
       20.872, 22.952, 22.616, 21.896, 21.432, 22.244, 22.588, 22.28 ,
       24.516, 25.112, 25.288, 24.34 , 24.852, 22.996, 22.108, 24.512,
       25.24 , 25.696])

In [66]:
Final_test_dataset = pd.read_csv('Final_test_dataset.csv')
Final_test_dataset

Date   ...  Daily global solar exposure (MJ/m*m)
0     1/11/2020  ...                                  23.2
1     2/11/2020  ...                                  26.8
2     3/11/2020  ...                                  26.9
3     4/11/2020  ...                                   5.5
4     5/11/2020  ...                                  23.1
..          ...  ...                                   ...
146  27/03/2021  ...                                   NaN
147  28/03/2021  ...                                   NaN
148  29/03/2021  ...                                   NaN
149  30/03/2021  ...                                   NaN
150  31/03/2021  ...                                   NaN

[151 rows x 8 columns]

In [71]:
Final_test_dataset['Minimum temperature (Degree C)'][61:151] = test_min_temp

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [72]:
Final_test_dataset['Minimum temperature (Degree C)'][61:151]

61     13.383084
62     13.419101
63     13.455117
64     13.092128
65     13.128144
         ...    
146     9.581615
147     9.617631
148     9.254642
149     9.290658
150     9.326675
Name: Minimum temperature (Degree C), Length: 90, dtype: float64

In [76]:
Final_test_dataset['Maximum temperature (Degree C)'][61:151] = test_max_temp

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [77]:
Final_test_dataset

Date   ...  Daily global solar exposure (MJ/m*m)
0     1/11/2020  ...                                  23.2
1     2/11/2020  ...                                  26.8
2     3/11/2020  ...                                  26.9
3     4/11/2020  ...                                   5.5
4     5/11/2020  ...                                  23.1
..          ...  ...                                   ...
146  27/03/2021  ...                                   NaN
147  28/03/2021  ...                                   NaN
148  29/03/2021  ...                                   NaN
149  30/03/2021  ...                                   NaN
150  31/03/2021  ...                                   NaN

[151 rows x 8 columns]

In [79]:
Final_test_dataset.to_csv('Final_test_dataset.csv')